//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodleQuestions.Pages.CreateQuestion {
    
    
    public partial class LoggedUserView {
        
        /// <summary>
        /// AnonymousUserView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MoodleQuestions.Pages.CreateQuestion.AnonymousUserView AnonymousUserView;
        
        /// <summary>
        /// SaveQuestionButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button SaveQuestionButton;
    }
}
