//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Content { get; set; }
        public double Fraction { get; set; }
    
        public virtual Question Questions { get; set; }
    }
}
