//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość odpowiedzi:.
        /// </summary>
        internal static string AnswerCountDropDownLabel {
            get {
                return ResourceManager.GetString("AnswerCountDropDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź:.
        /// </summary>
        internal static string AnswerLabelText {
            get {
                return ResourceManager.GetString("AnswerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor:.
        /// </summary>
        internal static string AuthorLabelText {
            get {
                return ResourceManager.GetString("AuthorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia ocena:.
        /// </summary>
        internal static string AverageRatingLabelText {
            get {
                return ResourceManager.GetString("AverageRatingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria:.
        /// </summary>
        internal static string CategoryLabelText {
            get {
                return ResourceManager.GetString("CategoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        internal static string CreationDateHeaderText {
            get {
                return ResourceManager.GetString("CreationDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia:.
        /// </summary>
        internal static string CreationDateLabelText {
            get {
                return ResourceManager.GetString("CreationDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        internal static string DetailsLabelText {
            get {
                return ResourceManager.GetString("DetailsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzone przed:.
        /// </summary>
        internal static string EndDateLabelText {
            get {
                return ResourceManager.GetString("EndDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena odpowiedzi:.
        /// </summary>
        internal static string FractionLabelText {
            get {
                return ResourceManager.GetString("FractionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma ocen cząstkowych jest nieprawidłowa.
        /// </summary>
        internal static string FractionValidatorErrorMessage {
            get {
                return ResourceManager.GetString("FractionValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj plik XML.
        /// </summary>
        internal static string GenerateXMLButtonText {
            get {
                return ResourceManager.GetString("GenerateXMLButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string NameHeaderText {
            get {
                return ResourceManager.GetString("NameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość pytań:.
        /// </summary>
        internal static string QuestionCountLabelText {
            get {
                return ResourceManager.GetString("QuestionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie:.
        /// </summary>
        internal static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie ocenione:.
        /// </summary>
        internal static string RatedQuestionCountLabelText {
            get {
                return ResourceManager.GetString("RatedQuestionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        internal static string RatingHeaderText {
            get {
                return ResourceManager.GetString("RatingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena:.
        /// </summary>
        internal static string RatingLabelText {
            get {
                return ResourceManager.GetString("RatingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzone po:.
        /// </summary>
        internal static string StartDateLabelText {
            get {
                return ResourceManager.GetString("StartDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        internal static string TypeLabelText {
            get {
                return ResourceManager.GetString("TypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie nieocenione:.
        /// </summary>
        internal static string UnratedQuestionCountLabelText {
            get {
                return ResourceManager.GetString("UnratedQuestionCountLabelText", resourceCulture);
            }
        }
    }
}
