//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie kontem.
        /// </summary>
        internal static string AccountManagePageTitle {
            get {
                return ResourceManager.GetString("AccountManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość odpowiedzi:.
        /// </summary>
        internal static string AnswerCountDropDownLabel {
            get {
                return ResourceManager.GetString("AnswerCountDropDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź:.
        /// </summary>
        internal static string AnswerLabelText {
            get {
                return ResourceManager.GetString("AnswerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor:.
        /// </summary>
        internal static string AuthorLabelText {
            get {
                return ResourceManager.GetString("AuthorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia ocena:.
        /// </summary>
        internal static string AverageRatingLabelText {
            get {
                return ResourceManager.GetString("AverageRatingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria:.
        /// </summary>
        internal static string CategoryLabelText {
            get {
                return ResourceManager.GetString("CategoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        internal static string ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        internal static string ChangePasswordHeader {
            get {
                return ResourceManager.GetString("ChangePasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdż nowe hasło.
        /// </summary>
        internal static string ConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        internal static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string ContactNavLink {
            get {
                return ResourceManager.GetString("ContactNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string ContactPageTitle {
            get {
                return ResourceManager.GetString("ContactPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tworzenie nowego pytania testowego..
        /// </summary>
        internal static string CreateQuestionPageSubtitle {
            get {
                return ResourceManager.GetString("CreateQuestionPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz pytanie.
        /// </summary>
        internal static string CreateQuestionPageTitle {
            get {
                return ResourceManager.GetString("CreateQuestionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz.
        /// </summary>
        internal static string CreateQuestionsPageNavLink {
            get {
                return ResourceManager.GetString("CreateQuestionsPageNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        internal static string CreationDateHeaderText {
            get {
                return ResourceManager.GetString("CreationDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia:.
        /// </summary>
        internal static string CreationDateLabelText {
            get {
                return ResourceManager.GetString("CreationDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecne hasło.
        /// </summary>
        internal static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        internal static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        internal static string DetailsLabelText {
            get {
                return ResourceManager.GetString("DetailsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzone przed:.
        /// </summary>
        internal static string EndDateLabelText {
            get {
                return ResourceManager.GetString("EndDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole jest wymagane..
        /// </summary>
        internal static string FieldIsRequiredMessage {
            get {
                return ResourceManager.GetString("FieldIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena odpowiedzi:.
        /// </summary>
        internal static string FractionLabelText {
            get {
                return ResourceManager.GetString("FractionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma ocen cząstkowych jest nieprawidłowa.
        /// </summary>
        internal static string FractionValidatorErrorMessage {
            get {
                return ResourceManager.GetString("FractionValidatorErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj plik XML.
        /// </summary>
        internal static string GenerateXMLButtonText {
            get {
                return ResourceManager.GetString("GenerateXMLButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        internal static string HelloText {
            get {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona umożliwia tworzenie i zarządzanie pytaniami dla platformy Moodle..
        /// </summary>
        internal static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skorzystaj z odpowiednich przycisków nawigacyjnych dostępnych na górze strony, aby wykonać odpowiednią akcję..
        /// </summary>
        internal static string HomePageInstructions {
            get {
                return ResourceManager.GetString("HomePageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główna.
        /// </summary>
        internal static string HomePageNavLink {
            get {
                return ResourceManager.GetString("HomePageNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie pytaniami testowymi.
        /// </summary>
        internal static string HomePageSubtitle {
            get {
                return ResourceManager.GetString("HomePageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widoczne dla innych:.
        /// </summary>
        internal static string IsVisibleLabelText {
            get {
                return ResourceManager.GetString("IsVisibleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś zalogowany/a jako:.
        /// </summary>
        internal static string LoggedInAsMessage {
            get {
                return ResourceManager.GetString("LoggedInAsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        internal static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moodle.
        /// </summary>
        internal static string MainLogoText {
            get {
                return ResourceManager.GetString("MainLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj.
        /// </summary>
        internal static string ManageQuestionsNavLink {
            get {
                return ResourceManager.GetString("ManageQuestionsNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie pytaniami testowymi..
        /// </summary>
        internal static string ManageQuestionsPageSubtitle {
            get {
                return ResourceManager.GetString("ManageQuestionsPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj pytaniami.
        /// </summary>
        internal static string ManageQuestionsPageTitle {
            get {
                return ResourceManager.GetString("ManageQuestionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło powinno składać się z co najmniej 6 znaków..
        /// </summary>
        internal static string MinimumPasswordLengthText {
            get {
                return ResourceManager.GetString("MinimumPasswordLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        internal static string NameHeaderText {
            get {
                return ResourceManager.GetString("NameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        internal static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie są takie same..
        /// </summary>
        internal static string PasswordConfimrationIsWrongMessage {
            get {
                return ResourceManager.GetString("PasswordConfimrationIsWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość pytań:.
        /// </summary>
        internal static string QuestionCountLabelText {
            get {
                return ResourceManager.GetString("QuestionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły pytania testowego..
        /// </summary>
        internal static string QuestionDetailsPageSubtitle {
            get {
                return ResourceManager.GetString("QuestionDetailsPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły pytania.
        /// </summary>
        internal static string QuestionDetailsPageTitle {
            get {
                return ResourceManager.GetString("QuestionDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie:.
        /// </summary>
        internal static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki.
        /// </summary>
        internal static string RaportsNavLink {
            get {
                return ResourceManager.GetString("RaportsNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki pytań studenta..
        /// </summary>
        internal static string RaportsPageSubtitle {
            get {
                return ResourceManager.GetString("RaportsPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki.
        /// </summary>
        internal static string RaportsPageTitle {
            get {
                return ResourceManager.GetString("RaportsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie ocenione:.
        /// </summary>
        internal static string RatedQuestionCountLabelText {
            get {
                return ResourceManager.GetString("RatedQuestionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena.
        /// </summary>
        internal static string RatingHeaderText {
            get {
                return ResourceManager.GetString("RatingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena:.
        /// </summary>
        internal static string RatingLabelText {
            get {
                return ResourceManager.GetString("RatingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        internal static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja nowego użytkownika..
        /// </summary>
        internal static string RegisterPageSubtitle {
            get {
                return ResourceManager.GetString("RegisterPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        internal static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stworzone po:.
        /// </summary>
        internal static string StartDateLabelText {
            get {
                return ResourceManager.GetString("StartDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ:.
        /// </summary>
        internal static string TypeLabelText {
            get {
                return ResourceManager.GetString("TypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie nieocenione:.
        /// </summary>
        internal static string UnratedQuestionCountLabelText {
            get {
                return ResourceManager.GetString("UnratedQuestionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string UserDropDownLabel {
            get {
                return ResourceManager.GetString("UserDropDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj.
        /// </summary>
        internal static string ViewQuestionsNavLink {
            get {
                return ResourceManager.GetString("ViewQuestionsNavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądanie widocznych pytań..
        /// </summary>
        internal static string ViewQuestionsPageSubtitle {
            get {
                return ResourceManager.GetString("ViewQuestionsPageSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj pytania.
        /// </summary>
        internal static string ViewQuestionsPageTitle {
            get {
                return ResourceManager.GetString("ViewQuestionsPageTitle", resourceCulture);
            }
        }
    }
}
